Repository opensearch-project/performance-analyzer, pull requests merged in 2024-06, with the labels that each got.

#657 Fixed the bug in CacheConfigMetricsCollector
  src/main/java/org/opensearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java
Labels: backport 2.x

#664 Bump PA to use 1.4.0 PA commons lib
  build.gradle
Labels: release, backport 2.x, v2.15.0

#671 Create opensearch-performance-analyzer.release-notes-2.15.0.0.md (#1)
  release-notes/release-notes/opensearch-performance-analyzer.release-notes-2.15.0.0.md
Labels: backport 2.x

#674 Move 2.15.0 release notes to correct location
  release-notes/opensearch-performance-analyzer.release-notes-2.15.0.0.md
Labels: release, backport 2.x, v2.15.0, backport 2.15
